### ISSUE TITLE
Add support for `:focus-visible` pseudo-class

### ISSUE THREAD

**Issue by cheton** [cheton/styled-ui#468]
https://developer.mozilla.org/en-US/docs/Web/CSS/:focus-visible

```css
:focus-visible {
  outline: -webkit-focus-ring-color auto 1px;
}
```
